

services:
  server:
    build: ./server
    container_name: tspo_server
    environment:
      - PORT=8080
      - DEFAULT_ROOM=lobby
    ports:
      - "8080:8080"
    expose:
      - 8080           
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8080/health')"]
      interval: 5s
      timeout: 2s
      retries: 20


  client1:
    build: ./client
    stdin_open: true          # מאפשר אינפוט מהטרמינל
    tty: true                 # TTY אינטראקטיבי
    environment:
      SERVER_URL: ws://server:8080/ws
      NICK: alice
      ROOM: lobby
      SHOW_OTHER_ROOMS: "off"
    depends_on:
      server:
        condition: service_healthy
    expose:
      - 8080

  client2:
    build: ./client
    stdin_open: true
    tty: true
    environment:
      SERVER_URL: ws://server:8080/ws
      NICK: bob
      ROOM: lobby
      SHOW_OTHER_ROOMS: "off"
    depends_on:
      server:
        condition: service_healthy
    expose:
      - 8080
